config/routes.rb
Rails.application.routes.draw do
  get 'add_part/:id', to: 'compositions#add_part', as: 'add_part'
  resources :compositions
  resources :herbs
  resources :classifications
  resources :hierarchies
  resources :effects
  resources :activities

  root 'herbs#index'

end

app/models/composition.rb
class Composition < ActiveRecord::Base
  has_many :herbs_compositions, dependent: :destroy
  has_many :herbs, through: :herbs_compositions

  accepts_nested_attributes_for :herbs_compositions, allow_destroy: true
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, only: [:show, :edit, :update, :destroy, :add_part]

  def index
    @compositions = Composition.all
  end

  def show
  end

  def new
    @composition = Composition.new
  end

  def edit
  end

  def create
    @composition = Composition.new(composition_params)

    if @composition.save
      redirect_to @composition, notice: 'Composition was successfully created.'
    else
      render :new
    end
  end

  def update
    if @composition.update(composition_params)
      redirect_to @composition, notice: 'Composition was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @composition.destroy
    redirect_to compositions_url, notice: 'Composition was successfully destroyed.'
  end

  def add_part
    @composition.herbs_compositions.build
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_composition
      @composition = Composition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def composition_params
      params.require(:composition).permit(:number, :name, :author, :description, herbs_compositions_attributes: [:id, :herb_id, :part, :_destroy])
    end
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/views/compositions/_form.html.erb
<%= form_for @composition, html: { class: "form-horizontal" } do |f| %>

  <%= render 'common/errors', object: @composition %>

  <div class="form-group">
    <%= f.label 'Номер', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :number, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Название', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Автор', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :author, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Описание', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_area :description, class: 'form-control', rows: '7' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/compositions/add_part.html.erb
<%= form_for @composition, html: { class: "form-horizontal" } do |f| %>

  <%= render 'common/errors', object: @composition %>

  <dl class="dl-horizontal">
    <dt>Номер:</dt>
    <dd><%= @composition.number %></dd>

    <dt>Название:</dt>
    <dd><%= @composition.name %></dd>

    <dt>Состав</dt>
    <dd>
      <table>
        <%= f.fields_for :herbs_compositions do |ingredient| %>
        <tr>
          <td><%= ingredient.collection_select :herb_id, Herb.all, :id, :name, {}, { class: 'form-control' } %></td>
          <td><%= ingredient.text_field :part, placeholder: 'Part', class: 'form-control' %></td>
          <td><%= ingredient.check_box :_destroy %> Удалить из сбора</td>
        </tr>
        <% end %>
      </table>
    </dd>
  </dl>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

<%= link_to 'Show', @composition %> |
<%= link_to 'Back', compositions_path %>

app/views/compositions/edit.html.erb
<h2 class="page-header">Редактирование сбора</h2>

<%= render 'form' %>

<%= link_to 'Show', @composition %> |
<%= link_to 'Back', compositions_path %>

app/views/compositions/index.html.erb
<%= link_to 'New Composition', new_composition_path %>

<h2 class="page-header">Список травяных сборов</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Номер</th>
      <th>Название</th>
      <th>Автор</th>
      <th>Описание</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @compositions.each do |composition| %>
      <tr>
        <td><%= composition.number %></td>
        <td><%= link_to composition.name, composition %></td>
        <td><%= composition.author %></td>
        <td><%= composition.description %></td>
        <td><%= link_to '', edit_composition_path(composition), class: 'fa fa-pencil' %></td>
        <td><%= link_to '', composition, method: :delete, class: 'fa fa-trash-o', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Composition', new_composition_path %>

app/views/compositions/new.html.erb
<h2 class="page-header">Новый сбор</h2>

<%= render 'form' %>

<%= link_to 'Back', compositions_path %>

app/views/compositions/show.html.erb
<h2 class="page-header"><%= @composition.name %></h2>

<dl class="dl-horizontal">
  <dt>Номер:</dt>
  <dd><%= @composition.number %></dd>

  <dt>Автор:</dt>
  <dd><%= @composition.author %></dd>

  <dt>Описание:</dt>
  <dd><%= @composition.description %></dd>

<% unless @composition.herbs.empty? %>
  <dt>Состав:</dt>
  <dd>
  <table class="table table-striped">
    <head>
      <tr><th>Название</th><th>Объём</th></tr>
    </head>
    <tbody>
    <% @composition.herbs_compositions.each do |ingredient| %>
      <tr>
        <td><%= link_to ingredient.herb.name, ingredient.herb %></td>
        <td><%= ingredient.part %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </dd>
<% end %>
</dl>

<%= link_to 'Add/Edit Parts', add_part_path(@composition) %> |
<%= link_to 'Edit', edit_composition_path(@composition) %> |
<%= link_to 'Back', compositions_path %>