config/routes.rb
Rails.application.routes.draw do
  get 'add_part/:id', to: 'compositions#add_part', as: 'add_part'
  resources :compositions
  resources :herbs
  resources :classifications
  resources :hierarchies
  resources :effects
  resources :activities

  root 'herbs#index'

end

app/models/herb.rb
class Herb < ActiveRecord::Base
  belongs_to :activity

  has_many :effects_herbs, dependent: :destroy
  has_many :effects, through: :effects_herbs

  has_many :herbs_compositions, dependent: :destroy
  has_many :compositions, through: :herbs_compositions

  has_many :classifications_herbs, dependent: :destroy
  has_many :classifications, through: :classifications_herbs

  default_scope { order(name: :asc) }
end

app/controllers/herbs_controller.rb
class HerbsController < ApplicationController
  before_action :set_herb, only: [:show, :edit, :update, :destroy]

  def index
    @herbs = Herb.all
  end

  def show
  end

  def new
    @herb = Herb.new
  end

  def edit
  end

  def create
    @herb = Herb.new(herb_params)

    if @herb.save
      redirect_to @herb, notice: 'Herb was successfully created.'
    else
      render :new
    end
  end

  def update
    if @herb.update(herb_params)
      redirect_to @herb, notice: 'Herb was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @herb.destroy
    redirect_to herbs_url, notice: 'Herb was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_herb
      @herb = Herb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def herb_params
      params.require(:herb).permit(:name, :latin_name, :popular_name, :description, :location, :activity_id, classification_ids: [], effect_ids: [])
    end
end

app/helpers/herbs_helper.rb
module HerbsHelper
end

app/views/herbs/_form.html.erb
<%= form_for @herb, html: { class: "form-horizontal" } do |f| %>

  <%= render 'common/errors', object: @herb %>

  <div class="form-group">
    <%= f.label 'Название', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Латинское название', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :latin_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Народное название', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :popular_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Описание', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_area :description, class: 'form-control', rows: '7' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Произростание', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :location, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Активность', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.collection_select :activity_id, Activity.all, :id, :level, {}, { class: 'form-control' } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Классификация', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.collection_select :classification_ids, Classification.all, :id, :name, {}, { multiple: true, size: "7", class: 'form-control' } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Воздействие', class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.collection_select :effect_ids, Effect.all, :id, :name, {}, { multiple: true, size: "7", class: 'form-control' } %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/herbs/edit.html.erb
<h2 class="page-header">Редактирование травы</h2>

<%= render 'form' %>

<%= link_to 'Show', @herb %> |
<%= link_to 'Back', herbs_path %>

app/views/herbs/index.html.erb
<%= link_to 'New Herb', new_herb_path %>

<h2 class="page-header">Список трав</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Название</th>
      <th>Латинское название</th>
      <th>Народное название</th>
      <th>Описание</th>
      <th>Произростание</th>
      <th>Активность</th>
      <th>Классификация</th>
      <th>Воздействие</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @herbs.each do |herb| %>
      <tr>
        <td><%= link_to herb.name, herb %></td>
        <td><%= herb.latin_name %></td>
        <td><%= herb.popular_name %></td>
        <td><%= herb.description %></td>
        <td><%= herb.location %></td>
        <td><%= herb.activity.level %></td>
        <td><%= herb.classifications.map { |item| item.name }.join(', ') %></td>
        <td><%= herb.effects.map { |item| item.name }.join(', ') %></td>
        <td><%= link_to '', edit_herb_path(herb), class: 'fa fa-pencil' %></td>
        <td><%= link_to '', herb, method: :delete, class: 'fa fa-trash-o', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Herb', new_herb_path %>

app/views/herbs/new.html.erb
<h2 class="page-header">Новая трава</h2>

<%= render 'form' %>

<%= link_to 'Back', herbs_path %>

app/views/herbs/show.html.erb
<h2 class="page-header"><%= @herb.name %></h2>

<dl class="dl-horizontal">
  <dt>Латинское название:</dt>
  <dd><%= @herb.latin_name %></dd>

  <dt>Народное название:</dt>
  <dd><%= @herb.popular_name %></dd>

  <dt>Описание:</dt>
  <dd><%= @herb.description %></dd>

  <dt>Произростание:</dt>
  <dd><%= @herb.location %></dd>

  <dt>Активность:</dt>
  <dd><%= @herb.activity.level %></dd>

  <dt>Классификация:</dt>
  <dd><%= @herb.classifications.map { |item| item.name }.join(', ') %></dd>

  <dt>Воздействие:</dt>
  <dd><%= @herb.effects.map { |item| item.name }.join(', ') %></dd>
</dl>

<%= link_to 'Edit', edit_herb_path(@herb) %> |
<%= link_to 'Back', herbs_path %>