config/routes.rb
Rails.application.routes.draw do
  get 'add_part/:id', to: 'compositions#add_part', as: 'add_part'
  resources :compositions
  resources :herbs
  resources :classifications
  resources :hierarchies
  resources :effects
  resources :activities

  root 'herbs#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :herbs
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = Activity.all
  end

  def show
  end

  def new
    @activity = Activity.new
  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to @activity, notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:level)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity, html: { class: "form-horizontal" } do |f| %>

  <%= render 'common/errors', object: @activity %>

  <div class="form-group">
    <%= f.label 'Уровень', class: 'col-sm-2 control-label' %>
  <div class="col-sm-6">
      <%= f.text_field :level, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h2 class="page-header">Редактирование активности</h2>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h2 class="page-header">Список активностей</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Уровень</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.level %></td>
        <td><%= link_to '', activity, class: 'fa fa-eye' %></td>
        <td><%= link_to '', edit_activity_path(activity), class: 'fa fa-pencil' %></td>
        <td><%= link_to '', activity, method: :delete, class: 'fa fa-trash-o', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h2 class="page-header">Новая активность</h2>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<h2 class="page-header"><%= @activity.level %></h2>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>