config/routes.rb
Rails.application.routes.draw do
  get 'add_part/:id', to: 'compositions#add_part', as: 'add_part'
  resources :compositions
  resources :herbs
  resources :classifications
  resources :hierarchies
  resources :effects
  resources :activities

  root 'herbs#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :herbs
end

app/models/classification.rb
class Classification < ActiveRecord::Base
  belongs_to :hierarchy
  belongs_to :classification
  has_many :classifications

  has_many :classifications_herbs, dependent: :destroy
  has_many :herbs, through: :classifications_herbs
end

app/models/classifications_herb.rb
class ClassificationsHerb < ActiveRecord::Base
  belongs_to :classification
  belongs_to :herb
end

app/models/composition.rb
class Composition < ActiveRecord::Base
  has_many :herbs_compositions, dependent: :destroy
  has_many :herbs, through: :herbs_compositions

  accepts_nested_attributes_for :herbs_compositions, allow_destroy: true
end

app/models/effect.rb
class Effect < ActiveRecord::Base
  has_many :effects_herbs, dependent: :destroy
  has_many :herbs, through: :effects_herbs
end

app/models/effects_herb.rb
class EffectsHerb < ActiveRecord::Base
  belongs_to :effect
  belongs_to :herb
end

app/models/herb.rb
class Herb < ActiveRecord::Base
  belongs_to :activity

  has_many :effects_herbs, dependent: :destroy
  has_many :effects, through: :effects_herbs

  has_many :herbs_compositions, dependent: :destroy
  has_many :compositions, through: :herbs_compositions

  has_many :classifications_herbs, dependent: :destroy
  has_many :classifications, through: :classifications_herbs

  default_scope { order(name: :asc) }
end

app/models/herbs_composition.rb
class HerbsComposition < ActiveRecord::Base
  belongs_to :herb
  belongs_to :composition
end

app/models/hierarchy.rb
class Hierarchy < ActiveRecord::Base
  has_many :classifications
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = Activity.all
  end

  def show
  end

  def new
    @activity = Activity.new
  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to @activity, notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:level)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/effects_controller.rb
class EffectsController < ApplicationController
  before_action :set_effect, only: [:show, :edit, :update, :destroy]

  def index
    @effects = Effect.all
  end

  def show
  end

  def new
    @effect = Effect.new
  end

  def edit
  end

  def create
    @effect = Effect.new(effect_params)

    if @effect.save
      redirect_to @effect, notice: 'Effect was successfully created.'
    else
      render :new
    end
  end

  def update
    if @effect.update(effect_params)
      redirect_to @effect, notice: 'Effect was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @effect.destroy
    redirect_to effects_url, notice: 'Effect was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_effect
      @effect = Effect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def effect_params
      params.require(:effect).permit(:description, :name)
    end
end

app/controllers/herbs_controller.rb
class HerbsController < ApplicationController
  before_action :set_herb, only: [:show, :edit, :update, :destroy]

  def index
    @herbs = Herb.all
  end

  def show
  end

  def new
    @herb = Herb.new
  end

  def edit
  end

  def create
    @herb = Herb.new(herb_params)

    if @herb.save
      redirect_to @herb, notice: 'Herb was successfully created.'
    else
      render :new
    end
  end

  def update
    if @herb.update(herb_params)
      redirect_to @herb, notice: 'Herb was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @herb.destroy
    redirect_to herbs_url, notice: 'Herb was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_herb
      @herb = Herb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def herb_params
      params.require(:herb).permit(:name, :latin_name, :popular_name, :description, :location, :activity_id, classification_ids: [], effect_ids: [])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/herbs_helper.rb
module HerbsHelper
end

app/helpers/hierarchies_helper.rb
module HierarchiesHelper
end

app/views/common/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this activity from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Phyto" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Phyto</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Сбор', compositions_path %></li>
            <li><%= link_to 'Травы', herbs_path %></li>
            <li><%= link_to 'Классификация', classifications_path %></li>
            <li><%= link_to 'Воздействие', effects_path %></li>
            <li><%= link_to 'Активность', activities_path %></li>
            <li><%= link_to 'Иерархия классов', hierarchies_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
<!--         <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Разделы</li>
              <li><%= link_to 'Сбор', compositions_path %></li>
              <li><%= link_to 'Травы', herbs_path %></li>
              <li><%= link_to 'Классификация', classifications_path %></li>
              <li><%= link_to 'Воздействие', effects_path %></li>
              <li><%= link_to 'Активность', activities_path %></li>
              <li><%= link_to 'Иерархия классов', hierarchies_path %></li>
            </ul>
          </div>
        </div> -->
      </div><!--/row-->

      <footer>
        <p>&copy; thomas 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>